/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.hops.examples.flink;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class codes extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2705619396434863703L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"codes\",\"namespace\":\"io.hops.examples.flink\",\"fields\":[{\"name\":\"code\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"scheme\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"subCode\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<codes> ENCODER =
      new BinaryMessageEncoder<codes>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<codes> DECODER =
      new BinaryMessageDecoder<codes>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<codes> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<codes> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<codes>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this codes to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a codes from a ByteBuffer. */
  public static codes fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String code;
  @Deprecated public java.lang.String scheme;
  @Deprecated public java.lang.String subCode;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public codes() {}

  /**
   * All-args constructor.
   * @param code The new value for code
   * @param scheme The new value for scheme
   * @param subCode The new value for subCode
   */
  public codes(java.lang.String code, java.lang.String scheme, java.lang.String subCode) {
    this.code = code;
    this.scheme = scheme;
    this.subCode = subCode;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return code;
    case 1: return scheme;
    case 2: return subCode;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: code = (java.lang.String)value$; break;
    case 1: scheme = (java.lang.String)value$; break;
    case 2: subCode = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'code' field.
   * @return The value of the 'code' field.
   */
  public java.lang.String getCode() {
    return code;
  }

  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.String value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'scheme' field.
   * @return The value of the 'scheme' field.
   */
  public java.lang.String getScheme() {
    return scheme;
  }

  /**
   * Sets the value of the 'scheme' field.
   * @param value the value to set.
   */
  public void setScheme(java.lang.String value) {
    this.scheme = value;
  }

  /**
   * Gets the value of the 'subCode' field.
   * @return The value of the 'subCode' field.
   */
  public java.lang.String getSubCode() {
    return subCode;
  }

  /**
   * Sets the value of the 'subCode' field.
   * @param value the value to set.
   */
  public void setSubCode(java.lang.String value) {
    this.subCode = value;
  }

  /**
   * Creates a new codes RecordBuilder.
   * @return A new codes RecordBuilder
   */
  public static io.hops.examples.flink.codes.Builder newBuilder() {
    return new io.hops.examples.flink.codes.Builder();
  }

  /**
   * Creates a new codes RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new codes RecordBuilder
   */
  public static io.hops.examples.flink.codes.Builder newBuilder(io.hops.examples.flink.codes.Builder other) {
    return new io.hops.examples.flink.codes.Builder(other);
  }

  /**
   * Creates a new codes RecordBuilder by copying an existing codes instance.
   * @param other The existing instance to copy.
   * @return A new codes RecordBuilder
   */
  public static io.hops.examples.flink.codes.Builder newBuilder(io.hops.examples.flink.codes other) {
    return new io.hops.examples.flink.codes.Builder(other);
  }

  /**
   * RecordBuilder for codes instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<codes>
    implements org.apache.avro.data.RecordBuilder<codes> {

    private java.lang.String code;
    private java.lang.String scheme;
    private java.lang.String subCode;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.hops.examples.flink.codes.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.code)) {
        this.code = data().deepCopy(fields()[0].schema(), other.code);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.scheme)) {
        this.scheme = data().deepCopy(fields()[1].schema(), other.scheme);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.subCode)) {
        this.subCode = data().deepCopy(fields()[2].schema(), other.subCode);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing codes instance
     * @param other The existing instance to copy.
     */
    private Builder(io.hops.examples.flink.codes other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.code)) {
        this.code = data().deepCopy(fields()[0].schema(), other.code);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.scheme)) {
        this.scheme = data().deepCopy(fields()[1].schema(), other.scheme);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.subCode)) {
        this.subCode = data().deepCopy(fields()[2].schema(), other.subCode);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'code' field.
      * @return The value.
      */
    public java.lang.String getCode() {
      return code;
    }

    /**
      * Sets the value of the 'code' field.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public io.hops.examples.flink.codes.Builder setCode(java.lang.String value) {
      validate(fields()[0], value);
      this.code = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'code' field.
      * @return This builder.
      */
    public io.hops.examples.flink.codes.Builder clearCode() {
      code = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'scheme' field.
      * @return The value.
      */
    public java.lang.String getScheme() {
      return scheme;
    }

    /**
      * Sets the value of the 'scheme' field.
      * @param value The value of 'scheme'.
      * @return This builder.
      */
    public io.hops.examples.flink.codes.Builder setScheme(java.lang.String value) {
      validate(fields()[1], value);
      this.scheme = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'scheme' field has been set.
      * @return True if the 'scheme' field has been set, false otherwise.
      */
    public boolean hasScheme() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'scheme' field.
      * @return This builder.
      */
    public io.hops.examples.flink.codes.Builder clearScheme() {
      scheme = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'subCode' field.
      * @return The value.
      */
    public java.lang.String getSubCode() {
      return subCode;
    }

    /**
      * Sets the value of the 'subCode' field.
      * @param value The value of 'subCode'.
      * @return This builder.
      */
    public io.hops.examples.flink.codes.Builder setSubCode(java.lang.String value) {
      validate(fields()[2], value);
      this.subCode = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'subCode' field has been set.
      * @return True if the 'subCode' field has been set, false otherwise.
      */
    public boolean hasSubCode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'subCode' field.
      * @return This builder.
      */
    public io.hops.examples.flink.codes.Builder clearSubCode() {
      subCode = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public codes build() {
      try {
        codes record = new codes();
        record.code = fieldSetFlags()[0] ? this.code : (java.lang.String) defaultValue(fields()[0]);
        record.scheme = fieldSetFlags()[1] ? this.scheme : (java.lang.String) defaultValue(fields()[1]);
        record.subCode = fieldSetFlags()[2] ? this.subCode : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<codes>
    WRITER$ = (org.apache.avro.io.DatumWriter<codes>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<codes>
    READER$ = (org.apache.avro.io.DatumReader<codes>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
