/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.hops.examples.flink;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class merchant extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5949692171643724724L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"merchant\",\"namespace\":\"io.hops.examples.flink\",\"fields\":[{\"name\":\"isoCode\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"name\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<merchant> ENCODER =
      new BinaryMessageEncoder<merchant>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<merchant> DECODER =
      new BinaryMessageDecoder<merchant>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<merchant> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<merchant> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<merchant>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this merchant to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a merchant from a ByteBuffer. */
  public static merchant fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String isoCode;
  @Deprecated public java.lang.String name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public merchant() {}

  /**
   * All-args constructor.
   * @param isoCode The new value for isoCode
   * @param name The new value for name
   */
  public merchant(java.lang.String isoCode, java.lang.String name) {
    this.isoCode = isoCode;
    this.name = name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return isoCode;
    case 1: return name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: isoCode = (java.lang.String)value$; break;
    case 1: name = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'isoCode' field.
   * @return The value of the 'isoCode' field.
   */
  public java.lang.String getIsoCode() {
    return isoCode;
  }

  /**
   * Sets the value of the 'isoCode' field.
   * @param value the value to set.
   */
  public void setIsoCode(java.lang.String value) {
    this.isoCode = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Creates a new merchant RecordBuilder.
   * @return A new merchant RecordBuilder
   */
  public static io.hops.examples.flink.merchant.Builder newBuilder() {
    return new io.hops.examples.flink.merchant.Builder();
  }

  /**
   * Creates a new merchant RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new merchant RecordBuilder
   */
  public static io.hops.examples.flink.merchant.Builder newBuilder(io.hops.examples.flink.merchant.Builder other) {
    return new io.hops.examples.flink.merchant.Builder(other);
  }

  /**
   * Creates a new merchant RecordBuilder by copying an existing merchant instance.
   * @param other The existing instance to copy.
   * @return A new merchant RecordBuilder
   */
  public static io.hops.examples.flink.merchant.Builder newBuilder(io.hops.examples.flink.merchant other) {
    return new io.hops.examples.flink.merchant.Builder(other);
  }

  /**
   * RecordBuilder for merchant instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<merchant>
    implements org.apache.avro.data.RecordBuilder<merchant> {

    private java.lang.String isoCode;
    private java.lang.String name;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.hops.examples.flink.merchant.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.isoCode)) {
        this.isoCode = data().deepCopy(fields()[0].schema(), other.isoCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing merchant instance
     * @param other The existing instance to copy.
     */
    private Builder(io.hops.examples.flink.merchant other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.isoCode)) {
        this.isoCode = data().deepCopy(fields()[0].schema(), other.isoCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'isoCode' field.
      * @return The value.
      */
    public java.lang.String getIsoCode() {
      return isoCode;
    }

    /**
      * Sets the value of the 'isoCode' field.
      * @param value The value of 'isoCode'.
      * @return This builder.
      */
    public io.hops.examples.flink.merchant.Builder setIsoCode(java.lang.String value) {
      validate(fields()[0], value);
      this.isoCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'isoCode' field has been set.
      * @return True if the 'isoCode' field has been set, false otherwise.
      */
    public boolean hasIsoCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'isoCode' field.
      * @return This builder.
      */
    public io.hops.examples.flink.merchant.Builder clearIsoCode() {
      isoCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public io.hops.examples.flink.merchant.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public io.hops.examples.flink.merchant.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public merchant build() {
      try {
        merchant record = new merchant();
        record.isoCode = fieldSetFlags()[0] ? this.isoCode : (java.lang.String) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<merchant>
    WRITER$ = (org.apache.avro.io.DatumWriter<merchant>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<merchant>
    READER$ = (org.apache.avro.io.DatumReader<merchant>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
