/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.hops.examples.flink;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class tags extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5372819239745423628L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"tags\",\"namespace\":\"io.hops.examples.flink\",\"fields\":[{\"name\":\"tracking_id\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<tags> ENCODER =
      new BinaryMessageEncoder<tags>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<tags> DECODER =
      new BinaryMessageDecoder<tags>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<tags> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<tags> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<tags>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this tags to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a tags from a ByteBuffer. */
  public static tags fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String tracking_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public tags() {}

  /**
   * All-args constructor.
   * @param tracking_id The new value for tracking_id
   */
  public tags(java.lang.String tracking_id) {
    this.tracking_id = tracking_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tracking_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tracking_id = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'tracking_id' field.
   * @return The value of the 'tracking_id' field.
   */
  public java.lang.String getTrackingId() {
    return tracking_id;
  }

  /**
   * Sets the value of the 'tracking_id' field.
   * @param value the value to set.
   */
  public void setTrackingId(java.lang.String value) {
    this.tracking_id = value;
  }

  /**
   * Creates a new tags RecordBuilder.
   * @return A new tags RecordBuilder
   */
  public static io.hops.examples.flink.tags.Builder newBuilder() {
    return new io.hops.examples.flink.tags.Builder();
  }

  /**
   * Creates a new tags RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new tags RecordBuilder
   */
  public static io.hops.examples.flink.tags.Builder newBuilder(io.hops.examples.flink.tags.Builder other) {
    return new io.hops.examples.flink.tags.Builder(other);
  }

  /**
   * Creates a new tags RecordBuilder by copying an existing tags instance.
   * @param other The existing instance to copy.
   * @return A new tags RecordBuilder
   */
  public static io.hops.examples.flink.tags.Builder newBuilder(io.hops.examples.flink.tags other) {
    return new io.hops.examples.flink.tags.Builder(other);
  }

  /**
   * RecordBuilder for tags instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<tags>
    implements org.apache.avro.data.RecordBuilder<tags> {

    private java.lang.String tracking_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.hops.examples.flink.tags.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tracking_id)) {
        this.tracking_id = data().deepCopy(fields()[0].schema(), other.tracking_id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing tags instance
     * @param other The existing instance to copy.
     */
    private Builder(io.hops.examples.flink.tags other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.tracking_id)) {
        this.tracking_id = data().deepCopy(fields()[0].schema(), other.tracking_id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'tracking_id' field.
      * @return The value.
      */
    public java.lang.String getTrackingId() {
      return tracking_id;
    }

    /**
      * Sets the value of the 'tracking_id' field.
      * @param value The value of 'tracking_id'.
      * @return This builder.
      */
    public io.hops.examples.flink.tags.Builder setTrackingId(java.lang.String value) {
      validate(fields()[0], value);
      this.tracking_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tracking_id' field has been set.
      * @return True if the 'tracking_id' field has been set, false otherwise.
      */
    public boolean hasTrackingId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tracking_id' field.
      * @return This builder.
      */
    public io.hops.examples.flink.tags.Builder clearTrackingId() {
      tracking_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public tags build() {
      try {
        tags record = new tags();
        record.tracking_id = fieldSetFlags()[0] ? this.tracking_id : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<tags>
    WRITER$ = (org.apache.avro.io.DatumWriter<tags>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<tags>
    READER$ = (org.apache.avro.io.DatumReader<tags>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
